
--Secuencia para la tabla TBL_CARGOS
CREATE SEQUENCE SQ_CARGOS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_CARGOS
    BEFORE INSERT ON TBL_CARGOS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_CARGO := SQ_CARGOS.nextval;

END;

--Secuencia para la tabla TBL_PERSONAS
CREATE SEQUENCE SQ_PERSONAS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_PERSONAS
    BEFORE INSERT ON TBL_PERSONAS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_PERSONA := SQ_PERSONAS.nextval;

END;

--Secuencia para la tabla TBL_TIPO_TRANSACCION
CREATE SEQUENCE SQ_TRANSACCION
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_TRANSACCION
    BEFORE INSERT ON TBL_TIPO_TRANSACCION
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_TIPO_TRANSACCION := SQ_TRANSACCION.nextval;

END;

--Secuencia para la tabla TBL_EMPLEADOS
CREATE SEQUENCE SQ_EMPLEADOS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_EMPLEADOS
    BEFORE INSERT ON TBL_EMPLEADOS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_EMPLEADO := SQ_EMPLEADOS.nextval;

END;

--Secuencia para la tabla TBL_CATEGORIAS
CREATE SEQUENCE SQ_CATEGORIAS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_CATEGORIAS
    BEFORE INSERT ON TBL_CATEGORIAS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_CATEGORIA := SQ_CATEGORIAS.nextval;

END;

--Secuencia para la tabla TBL_LIBRERIAS
CREATE SEQUENCE SQ_LIBRERIA
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_LIBRERIA
    BEFORE INSERT ON TBL_LIBRERIAS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_LIBRERIA := SQ_LIBRERIA.nextval;

END;

--Secuencia para la tabla TBL_SUCURSALES
CREATE SEQUENCE SQ_SUCURSALES
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_SUCURSALES
    BEFORE INSERT ON TBL_SUCURSALES
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_SUCURSAL := SQ_SUCURSALES.nextval;

END;

--Secuencia para la tabla TBL_LIBROS
CREATE SEQUENCE SQ_LIBROS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_LIBROS
    BEFORE INSERT ON TBL_LIBROS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_LIBRO:= SQ_LIBROS.nextval;

END;

--Secuencia para la tabla TBL_IDIOMAS
CREATE SEQUENCE SQ_IDIOMAS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_IDIOMAS
    BEFORE INSERT ON TBL_IDIOMAS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_IDIOMA:= SQ_IDIOMAS.nextval;

END;

--Secuencia para la tabla TBL_AUTORES
CREATE SEQUENCE SQ_AUTORES
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_AUTORES
    BEFORE INSERT ON TBL_AUTORES
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_AUTOR:= SQ_AUTORES.nextval;

END;

--Secuencia para la tabla TBL_FACTURAS
CREATE SEQUENCE SQ_FACTURAS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_FACTURAS
    BEFORE INSERT ON TBL_FACTURAS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_FACTURA := SQ_FACTURAS.nextval;

END;

--Secuencia para la tabla TBL_DETALLE_FACTURAS
CREATE SEQUENCE SQ_DETA_FACTURAS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_DETA_FACTURAS
    BEFORE INSERT ON TBL_DETALLE_FACTURAS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_DETA_FACTURA := SQ_DETA_FACTURAS.nextval;

END;

--Secuencia para la tabla TBL_GENEROS
CREATE SEQUENCE SQ_GENEROS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_GENEROS
    BEFORE INSERT ON TBL_GENEROS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_GENERO := SQ_GENEROS.nextval;

END;

--Secuencia para la tabla TBL_DESCUENTOS
CREATE SEQUENCE SQ_DESCUENTOS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_DESCUENTOS
    BEFORE INSERT ON TBL_DESCUENTOS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_DESCUENTO := SQ_DESCUENTOS.nextval;

END;

--Secuencia para la tabla TBL_PAGOS
CREATE SEQUENCE SQ_PAGOS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_PAGOS
    BEFORE INSERT ON TBL_PAGOS
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_PAGO := SQ_PAGOS.nextval;

END;

--Secuencia para la tabla TBL_TIPO_PAGO
CREATE SEQUENCE SQ_TIPO_PAGOS
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_TIPO_PAGOS
    BEFORE INSERT ON TBL_TIPO_PAGO
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_TIPO_PAGO := SQ_TIPO_PAGOS.nextval;

END;

--Secuencia para la tabla TBL_MORA
CREATE SEQUENCE SQ_MORA
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_MORA
    BEFORE INSERT ON TBL_MORA
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_MORA := SQ_MORA.nextval;

END;

--Secuencia para la tabla TBL_PRESTAMOS_LIBRO
CREATE SEQUENCE SQ_PRESTAMO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_PRESTAMO
    BEFORE INSERT ON TBL_PRESTAMOS_LIBRO
    FOR EACH ROW
DECLARE
BEGIN

    :NEW.ID_PRESTAMO := SQ_PRESTAMO.nextval;

END;

--Extras:
CREATE SEQUENCE SQ_COD1
START WITH 0801
INCREMENT BY 2;

CREATE SEQUENCE SQ_COD2
START WITH 1900
INCREMENT BY 3;

CREATE SEQUENCE SQ_COD3
START WITH 0
INCREMENT BY 123;
